In [32]:
import pandas as pd

In [33]:
more = pd.read_excel('more.xlsx', sheet_name='Cash orerating activities')

In [34]:
more.head()

   Symbol       Date  Cash from Operating Activities, Cumulative
0  CHP.HM 2013-12-31                                1.866311e+11
1  CHP.HM 2014-12-31                                2.973419e+11
2  CHP.HM 2015-12-31                                5.083332e+11
3  CHP.HM 2016-12-31                                3.371746e+11
4  CHP.HM 2017-12-31                                6.997493e+11

In [35]:
more['Year'] = pd.to_datetime(more['Date'],format='%d/%m-%Y').dt.year

In [36]:
more.drop(columns=['Symbol','Date'], inplace=True)

In [37]:
more.head()

   Cash from Operating Activities, Cumulative  Year
0                                1.866311e+11  2013
1                                2.973419e+11  2014
2                                5.083332e+11  2015
3                                3.371746e+11  2016
4                                6.997493e+11  2017

In [38]:
# more.to_excel('more_1.xlsx', index=False)

In [39]:
df = pd.read_excel('Data.xlsx')

In [40]:
df.head()

,Symbol,Year,"Dividend Payout Ratio, %","ROA Total Assets, Percent",ROE Common Equity %,Free Cash Flow,"Total Assets, Reported",Total Liabilities,Book value,Company Market Cap,Market to book ratio,Company_age,public_age,Exchange Name,GICS Industry Name,Type
0,CHP.HM,2014,1,6.331501,15.175416,1.979882e+11,3.321660e+12,1.900601e+12,1.421059e+12,1.824000e+12,1.283550,17,11,HOCHIMINH STOCK EXCHANGE,Independent Power and Renewable Electricity Pr...,Utilities
1,CHP.HM,2015,1,9.983413,20.545626,2.689276e+11,3.255272e+12,1.629185e+12,1.626087e+12,2.608190e+12,1.603967,17,11,HOCHIMINH STOCK EXCHANGE,Independent Power and Renewable Electricity Pr...,Utilities
2,CHP.HM,2016,1,8.132935,14.906333,1.717627e+11,3.083763e+12,1.413600e+12,1.670162e+12,2.608190e+12,1.561638,17,11,HOCHIMINH STOCK EXCHANGE,Independent Power and Renewable Electricity Pr...,Utilities
3,CHP.HM,2017,1,13.259479,22.429832,3.453495e+11,3.105531e+12,1.226634e+12,1.878897e+12,3.332687e+12,1.773746,17,11,HOCHIMINH STOCK EXCHANGE,Independent Power and Renewable Electricity Pr...,Utilities
4,CHP.HM,2018,1,3.220836,5.005674,-1.643881e+11,2.848967e+12,1.088086e+12,1.760880e+12,2.924428e+12,1.660776,17,11,HOCHIMINH STOCK EXCHANGE,Independent Power and Renewable Electricity Pr...,Utilities

In [41]:
more_1 = pd.read_excel('more_1.xlsx')

In [42]:
more_1

      Cash from Operating Activities, Cumulative  Year
0                                   1.866311e+11  2013
1                                   2.973419e+11  2014
2                                   5.083332e+11  2015
3                                   3.371746e+11  2016
4                                   6.997493e+11  2017
...                                          ...   ...
6073                                1.475888e+12  2017
6074                                4.695541e+11  2018
6075                                1.078454e+12  2019
6076                                5.603819e+11  2020
6077                               -9.637916e+11  2021

[6078 rows x 2 columns]

In [43]:
more_1 = more_1.drop_duplicates(subset='Year')

In [44]:
df_merged = pd.merge(df, more_1, on='Year', how='inner')

In [45]:
df_merged

,Symbol,Year,"Dividend Payout Ratio, %","ROA Total Assets, Percent",ROE Common Equity %,Free Cash Flow,"Total Assets, Reported",Total Liabilities,Book value,Company Market Cap,Market to book ratio,Company_age,public_age,Exchange Name,GICS Industry Name,Type,"Cash from Operating Activities, Cumulative"
0,CHP.HM,2014,1,6.331501,15.175416,1.979882e+11,3.321660e+12,1.900601e+12,1.421059e+12,1.824000e+12,1.283550,17,11,HOCHIMINH STOCK EXCHANGE,Independent Power and Renewable Electricity Pr...,Utilities,2.973419e+11
1,POM.HM,2014,0,-0.338181,-1.214096,2.294292e+11,9.369827e+12,7.029995e+12,2.339832e+12,1.565064e+12,0.668879,22,11,HOCHIMINH STOCK EXCHANGE,Metals & Mining,Material,2.973419e+11
2,V21.HN,2014,0,0.123886,1.329525,5.200922e+09,3.353529e+11,3.055495e+11,2.980338e+10,8.840000e+09,0.296611,16,11,HANOI STOCK EXCHANGE,Construction & Engineering,Industrials,2.973419e+11
3,LIG.HN,2014,0,1.350044,9.561633,4.579653e+10,1.457493e+12,1.287078e+12,1.704153e+11,7.906702e+10,0.463967,25,11,HANOI STOCK EXCHANGE,Construction & Engineering,Industrials,2.973419e+11
4,MCC.HN,2014,1,16.401106,19.098559,-5.394960e+09,6.193375e+10,7.666860e+09,5.426689e+10,5.705109e+10,1.051306,15,11,HANOI STOCK EXCHANGE,Construction Materials,Material,2.973419e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5723,DAG.HM,2021,1,0.314662,0.874079,4.491459e+10,2.028803e+12,1.349025e+12,6.797783e+11,5.972591e+11,0.878609,20,11,HOCHIMINH STOCK EXCHANGE,Building Products,Industrials,3.109158e+11
5724,PVL.HN,2021,0,4.237970,7.027156,1.674845e+10,4.094021e+11,1.569183e+11,2.524838e+11,2.665900e+11,1.055870,14,11,HANOI STOCK EXCHANGE,Real Estate Management & Development,Real_estate,3.109158e+11
5725,CCI.HM,2021,1,4.712435,9.737101,9.173168e+09,6.891628e+11,4.090719e+11,2.800909e+11,1.049188e+12,3.745885,29,11,HOCHIMINH STOCK EXCHANGE,Trading Companies & Distributors,Industrials,3.109158e+11
5726,PPP.HN,2021,0,11.209427,13.513555,1.591114e+10,1.560300e+11,3.944678e+10,1.165833e+11,5.729917e+10,0.491487,21,10,HANOI STOCK EXCHANGE,Pharmaceuticals,Health_care,3.109158e+11
5727,IJC.HM,2021,0,9.100405,17.897527,3.003108e+11,6.808654e+12,3.464858e+12,3.343797e+12,7.283091e+10,0.021781,14,11,HOCHIMINH STOCK EXCHANGE,Construction & Engineering,Industrials,3.109158e+11

In [46]:
# df_merged.to_excel('Dividend_payout_data.xlsx', index=False)