In [49]:
import pandas as pd
import numpy as np
import datetime

In [50]:
dividend = pd.read_excel('Dividend_payout.xlsx', sheet_name='Data')

In [51]:
more = pd.read_excel('more.xlsx', sheet_name='founded year')

In [52]:
dividend

,Symbol,Year,"Dividend Payout Ratio, %","ROA Total Assets, Percent",ROE Common Equity %,Free Cash Flow,"Total Assets, Reported",Total Liabilities,Book value,Company Market Cap,Market to book ratio
0,CHP.HM,2014,50.546666,6.331501,15.175416,1.979882e+11,3.321660e+12,1.900601e+12,1.421059e+12,1.824000e+12,1.283550
1,CHP.HM,2015,61.182867,9.983413,20.545626,2.689276e+11,3.255272e+12,1.629185e+12,1.626087e+12,2.608190e+12,1.603967
2,CHP.HM,2016,77.956368,8.132935,14.906333,1.717627e+11,3.083763e+12,1.413600e+12,1.670162e+12,2.608190e+12,1.561638
3,CHP.HM,2017,48.117528,13.259479,22.429832,3.453495e+11,3.105531e+12,1.226634e+12,1.878897e+12,3.332687e+12,1.773746
4,CHP.HM,2018,216.803357,3.220836,5.005674,-1.643881e+11,2.848967e+12,1.088086e+12,1.760880e+12,2.924428e+12,1.660776
...,...,...,...,...,...,...,...,...,...,...,...
5723,IJC.HM,2017,NaN,2.164981,7.298636,1.067126e+11,8.031767e+12,6.370528e+12,1.661239e+12,5.314563e+10,0.031992
5724,IJC.HM,2018,NaN,2.881718,12.332293,1.049349e+11,8.138196e+12,6.401485e+12,1.736711e+12,2.657281e+10,0.015301
5725,IJC.HM,2019,NaN,3.865497,15.334170,2.581668e+11,7.574266e+12,5.720370e+12,1.853895e+12,1.027312e+11,0.055414
5726,IJC.HM,2020,NaN,5.132003,13.809269,-3.838982e+11,6.841293e+12,3.645325e+12,3.195969e+12,3.166562e+10,0.009908
5727,IJC.HM,2021,NaN,9.100405,17.897527,3.003108e+11,6.808654e+12,3.464858e+12,3.343797e+12,7.283091e+10,0.021781

In [53]:
more.head()

   Symbol Date Became Public  Organization Founded Year
0  CHP.HM         2010-04-20                       2004
1  POM.HM         2010-04-20                       1999
2  V21.HN         2010-04-21                       2005
3  LIG.HN         2010-04-22                       1996
4  MCC.HN         2010-04-26                       2006

In [54]:
df = pd.merge(dividend, more, on='Symbol')

In [55]:
df.shape

(5728, 13)

In [56]:
df['publish_year'] = pd.to_datetime(df['Date Became Public'],format='%d/%m-%Y').dt.year

In [57]:
df['Company_age'] = 2021 - df['Organization Founded Year']

In [58]:
df['public_age'] = 2021 - df['publish_year']

In [59]:
df.drop(columns=['Date Became Public','Organization Founded Year','publish_year'], inplace=True)

In [60]:
df.shape

(5728, 13)

In [61]:
name = pd.read_excel('more.xlsx', sheet_name='Name')

In [62]:
Energy = ['Energy Equipment & Services','Oil, Gas & Consumable Fuels']
Material = ['Chemicals','Construction Materials','Containers & Packaging','Metals & Mining','Paper & Forest Products']
Industrials = ['Building Products','Construction & Engineering','Electrical Equipment',
               'Industrial Conglomerates','Machinery','Trading Companies & Distributors',
               'Commercial Services & Supplies','Professional Services','Air Freight & Logistics',
               'Airlines','Marine','Road & Rail','Transportation Infrastructure']
Consumer_discretionary = ['Auto Components','Automobiles','Household Durables','Hotels, Restaurants & Leisure','Textiles, Apparel & Luxury Goods',
                          'Diversified Consumer Services','Distributors','Specialty Retail','Leisure Products']
Consumer_staples = ['Beverages','Food Products','Tobacco','Household Products']
Health_care = ['Health Care Equipment & Supplies','Health Care Providers & Services','Pharmaceuticals']
Financials = ['Banks','Diversified Financial Services','Capital Markets','Insurance']
Information_technology = ['IT Services','Software','Communications Equipment','Electronic Equipment, Instruments & Components']
Communication_services = ['Diversified Telecommunication Services','Entertainment','Media']
Utilities = ['Electric Utilities','Gas Utilities','Water Utilities','Independent Power and Renewable Electricity Producers']
Real_estate = ['Real Estate Management & Development']

In [63]:
# Define the functions to divide the values based on labels
def type_func(x):
    if x in ['Energy Equipment & Services','Oil, Gas & Consumable Fuels']:
        return 'Energy'
    elif x in ['Chemicals','Construction Materials','Containers & Packaging','Metals & Mining','Paper & Forest Products']:
        return 'Material'
    elif x in ['Building Products','Construction & Engineering','Electrical Equipment','Industrial Conglomerates',
               'Machinery','Trading Companies & Distributors','Commercial Services & Supplies','Professional Services',
               'Air Freight & Logistics','Airlines','Marine','Road & Rail','Transportation Infrastructure']:
        return 'Industrials'
    elif x in ['Auto Components','Automobiles','Household Durables','Hotels, Restaurants & Leisure','Textiles, Apparel & Luxury Goods',
                          'Diversified Consumer Services','Distributors','Specialty Retail','Leisure Products']:
        return 'Consumer_discretionary'
    elif x in ['Beverages','Food Products','Tobacco','Household Products']:
        return 'Consumer_staples'
    elif x in ['Banks','Diversified Financial Services','Capital Markets','Insurance']:
        return 'Financials'
    elif x in ['IT Services','Software','Communications Equipment','Electronic Equipment, Instruments & Components']:
        return 'Information_technology'
    elif x in ['Diversified Telecommunication Services','Entertainment','Media']:
        return 'Communication_services'
    elif x in ['Electric Utilities','Gas Utilities','Water Utilities','Independent Power and Renewable Electricity Producers']:
        return 'Utilities'
    elif x in ['Health Care Equipment & Supplies','Health Care Providers & Services','Pharmaceuticals']:
        return 'Health_care'
    elif x in ['Real Estate Management & Development']:
        return 'Real_estate'
    else:
        return None

# def material_func(x):
#     return f'Material {x}'

# Apply the functions to create the new columns
name['Type'] = name['GICS Industry Name'].apply(type_func)

# Print the updated data frame
name

,Symbol,Company Common Name,Exchange Name,GICS Industry Name,Type
0,CHP.HM,Central Hydropower JSC,HOCHIMINH STOCK EXCHANGE,Independent Power and Renewable Electricity Pr...,Utilities
1,POM.HM,Pomina Steel Corp,HOCHIMINH STOCK EXCHANGE,Metals & Mining,Material
2,V21.HN,Vinaconex 21 JSC,HANOI STOCK EXCHANGE,Construction & Engineering,Industrials
3,LIG.HN,Licogi 13 JSC,HANOI STOCK EXCHANGE,Construction & Engineering,Industrials
4,MCC.HN,High Grade Brick Tile Corp,HANOI STOCK EXCHANGE,Construction Materials,Material
...,...,...,...,...,...
712,DAG.HM,Dong A Plastic Group JSC,HOCHIMINH STOCK EXCHANGE,Building Products,Industrials
713,PVL.HN,Viet Property Investment JSC,HANOI STOCK EXCHANGE,Real Estate Management & Development,Real_estate
714,CCI.HM,CuChi Commercial and Industrial Developing Inv...,HOCHIMINH STOCK EXCHANGE,Trading Companies & Distributors,Industrials
715,PPP.HN,Phong Phu Pharmaceutical JSC,HANOI STOCK EXCHANGE,Pharmaceuticals,Health_care
716,IJC.HM,Becamex Infrastructure Development JSC,HOCHIMINH STOCK EXCHANGE,Construction & Engineering,Industrials

In [64]:
name['Type'].value_counts()

Industrials               239
Material                  119
Real_estate                64
Financials                 59
Consumer_discretionary     57
Consumer_staples           57
Utilities                  38
Energy                     31
Health_care                23
Communication_services     16
Information_technology     14
Name: Type, dtype: int64

In [65]:
name.drop(columns=['Company Common Name'], inplace=True)

In [66]:
df_1 = pd.merge(df, name, on='Symbol')

In [67]:
df_1.shape

(5728, 16)

In [68]:
def transform_data(x):
    if x <= 0 or pd.isna(x):
        return 0
    else:
        return 1

# Áp dụng hàm chuyển đổi dữ liệu cho cột A
df_1['Dividend Payout Ratio, %'] = df_1['Dividend Payout Ratio, %'].apply(transform_data)

df_1

,Symbol,Year,"Dividend Payout Ratio, %","ROA Total Assets, Percent",ROE Common Equity %,Free Cash Flow,"Total Assets, Reported",Total Liabilities,Book value,Company Market Cap,Market to book ratio,Company_age,public_age,Exchange Name,GICS Industry Name,Type
0,CHP.HM,2014,1,6.331501,15.175416,1.979882e+11,3.321660e+12,1.900601e+12,1.421059e+12,1.824000e+12,1.283550,17,11,HOCHIMINH STOCK EXCHANGE,Independent Power and Renewable Electricity Pr...,Utilities
1,CHP.HM,2015,1,9.983413,20.545626,2.689276e+11,3.255272e+12,1.629185e+12,1.626087e+12,2.608190e+12,1.603967,17,11,HOCHIMINH STOCK EXCHANGE,Independent Power and Renewable Electricity Pr...,Utilities
2,CHP.HM,2016,1,8.132935,14.906333,1.717627e+11,3.083763e+12,1.413600e+12,1.670162e+12,2.608190e+12,1.561638,17,11,HOCHIMINH STOCK EXCHANGE,Independent Power and Renewable Electricity Pr...,Utilities
3,CHP.HM,2017,1,13.259479,22.429832,3.453495e+11,3.105531e+12,1.226634e+12,1.878897e+12,3.332687e+12,1.773746,17,11,HOCHIMINH STOCK EXCHANGE,Independent Power and Renewable Electricity Pr...,Utilities
4,CHP.HM,2018,1,3.220836,5.005674,-1.643881e+11,2.848967e+12,1.088086e+12,1.760880e+12,2.924428e+12,1.660776,17,11,HOCHIMINH STOCK EXCHANGE,Independent Power and Renewable Electricity Pr...,Utilities
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5723,IJC.HM,2017,0,2.164981,7.298636,1.067126e+11,8.031767e+12,6.370528e+12,1.661239e+12,5.314563e+10,0.031992,14,11,HOCHIMINH STOCK EXCHANGE,Construction & Engineering,Industrials
5724,IJC.HM,2018,0,2.881718,12.332293,1.049349e+11,8.138196e+12,6.401485e+12,1.736711e+12,2.657281e+10,0.015301,14,11,HOCHIMINH STOCK EXCHANGE,Construction & Engineering,Industrials
5725,IJC.HM,2019,0,3.865497,15.334170,2.581668e+11,7.574266e+12,5.720370e+12,1.853895e+12,1.027312e+11,0.055414,14,11,HOCHIMINH STOCK EXCHANGE,Construction & Engineering,Industrials
5726,IJC.HM,2020,0,5.132003,13.809269,-3.838982e+11,6.841293e+12,3.645325e+12,3.195969e+12,3.166562e+10,0.009908,14,11,HOCHIMINH STOCK EXCHANGE,Construction & Engineering,Industrials
5727,IJC.HM,2021,0,9.100405,17.897527,3.003108e+11,6.808654e+12,3.464858e+12,3.343797e+12,7.283091e+10,0.021781,14,11,HOCHIMINH STOCK EXCHANGE,Construction & Engineering,Industrials

In [69]:
df_1['Dividend Payout Ratio, %'].value_counts()

1    3324
0    2404
Name: Dividend Payout Ratio, %, dtype: int64

In [70]:
# df_1.to_excel('Data.xlsx', index=False)